import { PrismaClient } from "@prisma/client"; // Imports the PrismaClient class generated by Prisma, which is the gateway for all DB queries. Required to communicate with your Neon PostgreSQL database.

const globalForPrisma = globalThis as unknown as { // Creates a typed reference to the global object so we can store a Prisma client instance on it.
  prisma?: PrismaClient; // Adds an optional prisma property that can hold a single reusable PrismaClient instance (prevents multiple instances).
};                                               

export const db = 
  globalForPrisma.prisma ?? // If a Prisma client already exists (during dev hot reloads), reuse it — avoids opening new DB connections repeatedly.
  new PrismaClient({ // Otherwise create a brand-new PrismaClient — this manages connection pooling and all DB access.
    log: ["error", "warn"], // Only log warnings and errors, which keeps your dev console clean while still showing important issues.
  });                                               

if (process.env.NODE_ENV !== "production") {  // In development only (Next.js dev server hot reloads), run this block to persist the client globally.
  globalForPrisma.prisma = db;  // Saves the PrismaClient instance on the global object, so hot reloads don't create multiple DB connections.
}                                                   

export default db;   
